### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by cydemily** [diversario/node-ssdp#84]
```
socket.io-parser decoded 337517[null] as {"type":3,"nsp":"/","id":37517,"data":[null]} +29ms
  socket.io-client:socket calling ack 37517 with [null] +30ms
(node:7339) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 139): Error: timeout
  ssdp-client Sending an M-SEARCH request +188ms
  ssdp-client Sent M-SEARCH request: { message: 'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1982\r\nST: wifi_bulb\r\nMAN: "ssdp:discover"\r\nMX: 3\r\n\r\n' } +1ms
(node:7339) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 140): Error: timeout
(node:7339) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 141): Error: timeout
(node:7339) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 142): Error: timeout
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)
```

Met the issue several times, how to solve it?

**Comment by diversario** [comment]
@cydemily late to this, but seems like it's been resolved? Reopen this is you think there's a fix needed in `node-ssdp`, please.
